############################################################
# Dockerfile to build NGINX + PHP-FPM container images
# Based on Ubuntu
############################################################

FROM php:5.6-fpm
MAINTAINER Chicory <dev@chicory.co>


#--------------------------------------------------------------------------
# Patch OS and ENV
#--------------------------------------------------------------------------

# keep upstart quiet
RUN dpkg-divert --local --rename --add /sbin/initctl
RUN ln -sf /bin/true /sbin/initctl

# no tty
ENV DEBIAN_FRONTEND noninteractive


#--------------------------------------------------------------------------
# Install Packages
#--------------------------------------------------------------------------

RUN apt-get update --fix-missing
RUN apt-get install -y libmcrypt-dev
RUN apt-get install -y nginx supervisor
RUN apt-get install -y cron
RUN docker-php-ext-install mcrypt


#--------------------------------------------------------------------------
# Configure Services
#--------------------------------------------------------------------------

# stop supervisor and nginx service as we'll run it manually
RUN service supervisor stop
RUN service nginx stop

# install configurations for nginx and supervisord
COPY supervisor.conf /etc/supervisor/conf.d/
# COPY nginx.conf /etc/nginx/nginx.conf
COPY nginx_asaf.conf /etc/nginx/nginx.conf

# install app
COPY . /var/www
RUN chown -R www-data:www-data /var/www


# RUN mkdir -p /etc/periodic/hourly
# ADD ./scripts/kill_long_processes.sh /etc/periodic/hourly/kill_long_processes.sh
# RUN chmod +x /etc/periodic/hourly/kill_long_processes.sh
# RUN crontab -l | { cat; echo "00    00       *       *       *       /etc/periodic/hourly/kill_long_processes.sh"; } | crontab -

#--------------------------------------------------------------------------
# Run Services
#--------------------------------------------------------------------------

ENTRYPOINT supervisord
EXPOSE 80
