FROM centos:7
RUN yum -y install epel-release
RUN yum -y update
RUN yum -y install nginx
RUN yum -y install php php-cli php-fpm php-mysqlnd php-zip php-devel php-gd php-mcrypt php-mbstring php-curl php-xml php-pear php-bcmath php-json
ADD index.html /usr/share/nginx/html/index.html
ADD yehuda_modify.html /usr/share/nginx/html/yehuda_modify.html
COPY nginx.conf  /etc/nginx/nginx.conf     
COPY php.ini    /etc/php.ini              
RUN chmod a+x /usr/bin/systemctl
ADD phpinfo.php /usr/share/nginx/html/phpinfo.php
EXPOSE 80/tcp
CMD ["php-fpm" && tail -F /var/log/php-fpm-error.log]"
CMD ["nginx", "-g daemon off;"]
